# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencenaturalarea',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='occurrencetaxon',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
