# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceobservation',
            name='observation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occurrenceobservation',
            name='recording_datetime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='affiliation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='email',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='phone1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='phone2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='street_address',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
