# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170628_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grank',
            old_name='grank',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='nrank',
            old_name='nrank',
            new_name='name',
        ),
        migrations.AddField(
            model_name='cmstatus',
            name='code',
            field=models.TextField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmstatus',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmstatus',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementspecies',
            name='cm_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CmStatus'),
        ),
        migrations.AddField(
            model_name='elementspecies',
            name='g_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.GRank'),
        ),
        migrations.AddField(
            model_name='elementspecies',
            name='n_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.NRank'),
        ),
        migrations.AddField(
            model_name='elementspecies',
            name='s_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SRank'),
        ),
        migrations.AddField(
            model_name='grank',
            name='code',
            field=models.TextField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nrank',
            name='code',
            field=models.TextField(default='', unique=True),
            preserve_default=False,
        ),
    ]
