# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170717_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamanimaldetails',
            name='pemso_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamanimaldetails',
            name='stream_name_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
