# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_occurrencecategory_main_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('affiliation', models.TextField()),
                ('phone1', models.TextField()),
                ('phone2', models.TextField()),
                ('email', models.TextField()),
                ('street_address', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='OccurenceNaturalArea',
            new_name='OccurrenceNaturalArea',
        ),
        migrations.RenameModel(
            old_name='OccurenceTaxon',
            new_name='OccurrenceTaxon',
        ),
    ]
