# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170628_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmstatus',
            name='status',
        ),
        migrations.RemoveField(
            model_name='srank',
            name='srank',
        ),
    ]
