# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170721_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceobservation',
            name='recording_station',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
