# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170628_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_common', models.TextField()),
                ('name_sci', models.TextField()),
                ('tsn', models.IntegerField(blank=True)),
                ('synonym', models.TextField(blank=True)),
                ('second_common', models.TextField(blank=True)),
                ('third_common', models.TextField(blank=True)),
                ('element_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ElementSpecies')),
            ],
        ),
        migrations.RemoveField(
            model_name='occurrencetaxon',
            name='species_element',
        ),
        migrations.AddField(
            model_name='occurrencetaxon',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Species'),
        ),
    ]
