# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170628_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='phylum',
        ),
        migrations.RemoveField(
            model_name='elementspecies',
            name='family',
        ),
        migrations.RemoveField(
            model_name='elementspecies',
            name='first_common',
        ),
        migrations.RemoveField(
            model_name='elementspecies',
            name='name_sci',
        ),
        migrations.RemoveField(
            model_name='elementspecies',
            name='second_common',
        ),
        migrations.RemoveField(
            model_name='elementspecies',
            name='synonym',
        ),
        migrations.RemoveField(
            model_name='elementspecies',
            name='third_common',
        ),
        migrations.RemoveField(
            model_name='elementspecies',
            name='tsn',
        ),
        migrations.AddField(
            model_name='species',
            name='family',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='species',
            name='family_common',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='species',
            name='phylum',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='species',
            name='phylum_common',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Phylum',
        ),
    ]
