# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170721_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceobservation',
            name='reporter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='core.PointOfContact'),
            preserve_default=False,
        ),
    ]
