# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170725_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencenaturalarea',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='occurrencetaxon',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
