# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170629_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementspecies',
            name='native',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='parts_collected',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='specimen_collected',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='specimen_number',
            field=models.NullBooleanField(default=False),
        ),
    ]
