# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170629_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofcontact',
            name='affiliation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='phone1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='phone2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='street_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
