# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170711_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencetaxon',
            name='details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TaxonDetails'),
        ),
    ]
