# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 14:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalLifestages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egg', models.IntegerField()),
                ('egg_mass', models.IntegerField()),
                ('nest', models.IntegerField()),
                ('early_instar_larva', models.IntegerField()),
                ('larva', models.IntegerField()),
                ('late_instar_larva', models.IntegerField()),
                ('early_instar_nymph', models.IntegerField()),
                ('nymph', models.IntegerField()),
                ('late_instar_nymph', models.IntegerField()),
                ('early_pupa', models.IntegerField()),
                ('pupa', models.IntegerField()),
                ('late_pupa', models.IntegerField()),
                ('juvenile', models.IntegerField()),
                ('immature', models.IntegerField()),
                ('subadult', models.IntegerField()),
                ('adult', models.IntegerField()),
                ('adult_pregnant_or_young', models.IntegerField()),
                ('senescent', models.IntegerField()),
                ('unknown', models.IntegerField()),
                ('na', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AquaticHabitatCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AquaticSampler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CmStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DayTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiseasesAndAbnormalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElementNaturalAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natural_area_code_nac', models.TextField(blank=True, default='')),
                ('general_description', models.TextField(blank=True, default='')),
                ('area', models.FloatField(null=True)),
                ('landscape_position', models.TextField(blank=True, default='')),
                ('cm_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.CmStatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElementSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native', models.NullBooleanField(default=True)),
                ('other_code', models.TextField(blank=True)),
                ('ibp_english', models.CharField(blank=True, default='', max_length=4)),
                ('ibp_scientific', models.CharField(blank=True, default='', max_length=6)),
                ('bblab_number', models.CharField(blank=True, default='', max_length=6)),
                ('nrcs_usda_symbol', models.TextField(blank=True, default='')),
                ('synonym_nrcs_usda_symbol', models.TextField(blank=True, default='')),
                ('epa_numeric_code', models.TextField(blank=True, default='')),
                ('cm_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.CmStatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HmfeiLocalAbundance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IucnRedListCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LakeMicrohabitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoticHabitatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MushroomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccurrenceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('main_cat', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccurrenceNaturalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('version', models.IntegerField(default=0)),
                ('released', models.BooleanField(default=False)),
                ('inclusion_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('natural_area_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.ElementNaturalAreas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccurrenceObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('recording_datetime', models.DateField(blank=True, null=True)),
                ('recording_station', models.TextField(blank=True, default='', null=True)),
                ('daytime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.DayTime')),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceTaxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('version', models.IntegerField(default=0)),
                ('released', models.BooleanField(default=False)),
                ('inclusion_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='image_height', max_length=1000, upload_to='images/%Y/%m/', width_field='image_width')),
                ('thumbnail', models.ImageField(blank=True, height_field='thumb_height', max_length=1000, upload_to='images/%Y/%m/', width_field='thumb_width')),
                ('image_width', models.PositiveIntegerField()),
                ('image_height', models.PositiveIntegerField()),
                ('thumb_width', models.PositiveIntegerField(null=True)),
                ('thumb_height', models.PositiveIntegerField(null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('occurrence_fk', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='PointOfContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('affiliation', models.TextField(blank=True, default='', null=True)),
                ('phone1', models.TextField(blank=True, default='', null=True)),
                ('phone2', models.TextField(blank=True, default='', null=True)),
                ('email', models.TextField(blank=True, default='', null=True)),
                ('street_address', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PondLakeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PondLakeUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preservative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecordingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecordOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegionalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShorelineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlimeMoldClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlimeMoldLifestages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlimeMoldMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_common', models.TextField()),
                ('name_sci', models.TextField()),
                ('tsn', models.PositiveIntegerField(null=True)),
                ('synonym', models.TextField(blank=True, default='')),
                ('second_common', models.TextField(blank=True, default='')),
                ('third_common', models.TextField(blank=True, default='')),
                ('family', models.TextField(blank=True, default='')),
                ('family_common', models.TextField(blank=True, default='')),
                ('phylum', models.TextField(blank=True, default='')),
                ('phylum_common', models.TextField(blank=True, default='')),
                ('element_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.ElementSpecies')),
            ],
        ),
        migrations.CreateModel(
            name='SRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreamDesignatedUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreamSubstracte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artificial', models.FloatField()),
                ('bedrock', models.FloatField()),
                ('boulder', models.FloatField()),
                ('boulder_slab', models.FloatField()),
                ('clay_hardpan', models.FloatField()),
                ('cobble', models.FloatField()),
                ('fine_detritus', models.FloatField()),
                ('gravel', models.FloatField()),
                ('leafpack_woody_debris', models.FloatField()),
                ('muck', models.FloatField()),
                ('sand', models.FloatField()),
                ('silt', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxonDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TerrestrialSampler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TerrestrialStratum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsfwsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.PositiveIntegerField(null=True)),
                ('specimen_collected', models.NullBooleanField(default=False)),
                ('parts_collected', models.NullBooleanField(default=False)),
                ('specimen_number', models.NullBooleanField(default=False)),
                ('repository', models.TextField(blank=True, default='', null=True)),
                ('preservative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Preservative')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Storage')),
            ],
        ),
        migrations.CreateModel(
            name='WaterFlowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WetlandConnectivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WetlandHabitatFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WetlandLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WetlandType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WetlandVetegationStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buttonbush', models.FloatField()),
                ('cattail', models.FloatField()),
                ('ferns', models.FloatField()),
                ('forbs', models.FloatField()),
                ('phragmites', models.FloatField()),
                ('sedges', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LandAnimalDetails',
            fields=[
                ('taxondetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfdcore.TaxonDetails')),
                ('diseases_and_abnormalities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.DiseasesAndAbnormalities')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Gender')),
                ('lifestages', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.AnimalLifestages')),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Marks')),
                ('sampler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.TerrestrialSampler')),
                ('stratum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.TerrestrialStratum')),
            ],
            options={
                'abstract': False,
            },
            bases=('nfdcore.taxondetails',),
        ),
        migrations.CreateModel(
            name='PlantDetails',
            fields=[
                ('taxondetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfdcore.TaxonDetails')),
            ],
            bases=('nfdcore.taxondetails',),
        ),
        migrations.CreateModel(
            name='PondLakeAnimalDetails',
            fields=[
                ('taxondetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfdcore.TaxonDetails')),
                ('lentic_size_acres_aprox', models.IntegerField()),
                ('lentic_size_squaremeters_aprox', models.IntegerField()),
                ('lentic_size_acres_exact', models.DecimalField(decimal_places=1, max_digits=6)),
                ('lentic_size_squaremeters_exact', models.DecimalField(decimal_places=1, max_digits=8)),
                ('pond_lake_name', models.TextField()),
                ('microhabitat_comments', models.TextField()),
                ('diseases_and_abnormalities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.DiseasesAndAbnormalities')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Gender')),
                ('lifestages', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.AnimalLifestages')),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Marks')),
                ('microhabitat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.LakeMicrohabitat')),
                ('pond_lake_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.PondLakeType')),
                ('pond_lake_use', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.PondLakeUse')),
                ('sampler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.AquaticSampler')),
                ('shoreline_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.ShorelineType')),
            ],
            options={
                'abstract': False,
            },
            bases=('nfdcore.taxondetails', models.Model),
        ),
        migrations.CreateModel(
            name='SlimeMoldDetails',
            fields=[
                ('taxondetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfdcore.TaxonDetails')),
                ('slime_mold_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.SlimeMoldClass')),
                ('slime_mold_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.SlimeMoldMedia')),
            ],
            bases=('nfdcore.taxondetails',),
        ),
        migrations.CreateModel(
            name='StreamAnimalDetails',
            fields=[
                ('taxondetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfdcore.TaxonDetails')),
                ('stream_name_1', models.TextField()),
                ('stream_name_2', models.TextField(blank=True, null=True)),
                ('pemso_code', models.TextField(blank=True, null=True)),
                ('channel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.ChannelType')),
                ('designated_use', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.StreamDesignatedUse')),
                ('diseases_and_abnormalities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.DiseasesAndAbnormalities')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Gender')),
                ('hmfei_local_abundance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.HmfeiLocalAbundance')),
                ('lifestages', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.AnimalLifestages')),
                ('lotic_habitat_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.LoticHabitatType')),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Marks')),
                ('sampler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.AquaticSampler')),
                ('substrate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.StreamSubstracte')),
                ('water_flow_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.WaterFlowType')),
            ],
            options={
                'abstract': False,
            },
            bases=('nfdcore.taxondetails',),
        ),
        migrations.CreateModel(
            name='WetlandAnimalDetails',
            fields=[
                ('taxondetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfdcore.TaxonDetails')),
                ('lentic_size_acres_aprox', models.IntegerField()),
                ('lentic_size_squaremeters_aprox', models.IntegerField()),
                ('lentic_size_acres_exact', models.DecimalField(decimal_places=1, max_digits=6)),
                ('lentic_size_squaremeters_exact', models.DecimalField(decimal_places=1, max_digits=8)),
                ('wetland_name', models.TextField()),
                ('active_management', models.NullBooleanField()),
                ('connectivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.WetlandConnectivity')),
                ('diseases_and_abnormalities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.DiseasesAndAbnormalities')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Gender')),
                ('habitat_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.WetlandHabitatFeature')),
                ('lifestages', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.AnimalLifestages')),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Marks')),
                ('sampler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.AquaticSampler')),
                ('vegetation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.WetlandVetegationStructure')),
                ('water_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.WaterSource')),
                ('wetland_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.WetlandLocation')),
                ('wetland_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.WetlandType')),
            ],
            options={
                'abstract': False,
            },
            bases=('nfdcore.taxondetails', models.Model),
        ),
        migrations.AddField(
            model_name='occurrencetaxon',
            name='details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.TaxonDetails'),
        ),
        migrations.AddField(
            model_name='occurrencetaxon',
            name='observation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nfdcore.OccurrenceObservation'),
        ),
        migrations.AddField(
            model_name='occurrencetaxon',
            name='occurrence_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.OccurrenceCategory'),
        ),
        migrations.AddField(
            model_name='occurrencetaxon',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Species'),
        ),
        migrations.AddField(
            model_name='occurrencetaxon',
            name='voucher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.Voucher'),
        ),
        migrations.AddField(
            model_name='occurrenceobservation',
            name='record_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.RecordOrigin'),
        ),
        migrations.AddField(
            model_name='occurrenceobservation',
            name='recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recorder', to='nfdcore.PointOfContact'),
        ),
        migrations.AddField(
            model_name='occurrenceobservation',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='nfdcore.PointOfContact'),
        ),
        migrations.AddField(
            model_name='occurrenceobservation',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Season'),
        ),
        migrations.AddField(
            model_name='occurrenceobservation',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifier', to='nfdcore.PointOfContact'),
        ),
        migrations.AddField(
            model_name='occurrencenaturalarea',
            name='observation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nfdcore.OccurrenceObservation'),
        ),
        migrations.AddField(
            model_name='occurrencenaturalarea',
            name='occurrence_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.OccurrenceCategory'),
        ),
        migrations.AddField(
            model_name='elementspecies',
            name='g_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.GRank'),
        ),
        migrations.AddField(
            model_name='elementspecies',
            name='iucn_red_list_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.IucnRedListCategory'),
        ),
        migrations.AddField(
            model_name='elementspecies',
            name='mushroom_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.MushroomGroup'),
        ),
        migrations.AddField(
            model_name='elementspecies',
            name='n_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.NRank'),
        ),
        migrations.AddField(
            model_name='elementspecies',
            name='oh_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.RegionalStatus'),
        ),
        migrations.AddField(
            model_name='elementspecies',
            name='s_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.SRank'),
        ),
        migrations.AddField(
            model_name='elementspecies',
            name='usfws_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.UsfwsStatus'),
        ),
        migrations.AddField(
            model_name='elementnaturalareas',
            name='g_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.GRank'),
        ),
        migrations.AddField(
            model_name='elementnaturalareas',
            name='n_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.NRank'),
        ),
        migrations.AddField(
            model_name='elementnaturalareas',
            name='s_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.SRank'),
        ),
    ]
