# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='second_common',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='synonym',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='third_common',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
