# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0002_auto_20170828_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencenaturalarea',
            name='released_versions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='occurrencetaxon',
            name='released_versions',
            field=models.IntegerField(default=0),
        ),
    ]
