# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0003_auto_20170830_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementspecies',
            name='bblab_number',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='elementspecies',
            name='epa_numeric_code',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='elementspecies',
            name='ibp_english',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='elementspecies',
            name='ibp_scientific',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='elementspecies',
            name='nrcs_usda_symbol',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='elementspecies',
            name='other_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elementspecies',
            name='synonym_nrcs_usda_symbol',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
