# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0004_auto_20170901_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CanopyCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConiferDetails',
            fields=[
                ('taxondetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfdcore.TaxonDetails')),
                ('area_ranges', models.TextField(blank=True, null=True)),
                ('leap_land_cover_category', models.TextField(blank=True, null=True)),
                ('aspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Aspect')),
            ],
            options={
                'abstract': False,
            },
            bases=('nfdcore.taxondetails',),
        ),
        migrations.CreateModel(
            name='ConiferLifestages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetative', models.FloatField(blank=True, default=0.0, null=True)),
                ('immature_ovulate_cones', models.FloatField(blank=True, default=0.0, null=True)),
                ('mature_ovulate_cones', models.FloatField(blank=True, default=0.0, null=True)),
                ('spent_ovulate_cones', models.FloatField(blank=True, default=0.0, null=True)),
                ('immature_pollen_cones', models.FloatField(blank=True, default=0.0, null=True)),
                ('mature_pollen_cones', models.FloatField(blank=True, default=0.0, null=True)),
                ('spent_pollen_cones', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisturbanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browse', models.FloatField(blank=True, default=0.0, null=True)),
                ('collecting', models.FloatField(blank=True, default=0.0, null=True)),
                ('disease_pest', models.FloatField(blank=True, default=0.0, null=True)),
                ('mowing', models.FloatField(blank=True, default=0.0, null=True)),
                ('trampling', models.FloatField(blank=True, default=0.0, null=True)),
                ('vehicle_traffic', models.FloatField(blank=True, default=0.0, null=True)),
                ('woody_plant_removal', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EarthwormEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casting_piles', models.FloatField(blank=True, default=0.0, null=True)),
                ('compacted_soil', models.FloatField(blank=True, default=0.0, null=True)),
                ('individuals', models.FloatField(blank=True, default=0.0, null=True)),
                ('layered_castings', models.FloatField(blank=True, default=0.0, null=True)),
                ('middens', models.FloatField(blank=True, default=0.0, null=True)),
                ('no_evidence', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FernDetails',
            fields=[
                ('taxondetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfdcore.TaxonDetails')),
                ('area_ranges', models.TextField(blank=True, null=True)),
                ('leap_land_cover_category', models.TextField(blank=True, null=True)),
                ('aspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Aspect')),
                ('disturbance_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.DisturbanceType')),
                ('earthworm_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.EarthwormEvidence')),
            ],
            options={
                'abstract': False,
            },
            bases=('nfdcore.taxondetails',),
        ),
        migrations.CreateModel(
            name='FernLifestages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloweringPlantDetails',
            fields=[
                ('taxondetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfdcore.TaxonDetails')),
                ('area_ranges', models.TextField(blank=True, null=True)),
                ('leap_land_cover_category', models.TextField(blank=True, null=True)),
                ('aspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Aspect')),
                ('disturbance_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.DisturbanceType')),
                ('earthworm_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.EarthwormEvidence')),
            ],
            options={
                'abstract': False,
            },
            bases=('nfdcore.taxondetails',),
        ),
        migrations.CreateModel(
            name='FloweringPlantLifestages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralHabitatCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroundSurface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandscapePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoistureRegime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MossDetails',
            fields=[
                ('taxondetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfdcore.TaxonDetails')),
                ('area_ranges', models.TextField(blank=True, null=True)),
                ('leap_land_cover_category', models.TextField(blank=True, null=True)),
                ('aspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Aspect')),
                ('disturbance_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.DisturbanceType')),
                ('earthworm_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.EarthwormEvidence')),
                ('general_habitat_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.GeneralHabitatCategory')),
                ('ground_surface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.GroundSurface')),
                ('landscape_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.LandscapePosition')),
            ],
            options={
                'abstract': False,
            },
            bases=('nfdcore.taxondetails',),
        ),
        migrations.CreateModel(
            name='MossLifestages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreamSubstrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artificial', models.FloatField(blank=True, default=0.0, null=True)),
                ('bedrock', models.FloatField(blank=True, default=0.0, null=True)),
                ('boulder', models.FloatField(blank=True, default=0.0, null=True)),
                ('boulder_slab', models.FloatField(blank=True, default=0.0, null=True)),
                ('clay_hardpan', models.FloatField(blank=True, default=0.0, null=True)),
                ('cobble', models.FloatField(blank=True, default=0.0, null=True)),
                ('fine_detritus', models.FloatField(blank=True, default=0.0, null=True)),
                ('gravel', models.FloatField(blank=True, default=0.0, null=True)),
                ('leafpack_woody_debris', models.FloatField(blank=True, default=0.0, null=True)),
                ('muck', models.FloatField(blank=True, default=0.0, null=True)),
                ('sand', models.FloatField(blank=True, default=0.0, null=True)),
                ('silt', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plantdetails',
            name='taxondetails_ptr',
        ),
        migrations.RemoveField(
            model_name='slimemoldlifestages',
            name='code',
        ),
        migrations.RemoveField(
            model_name='slimemoldlifestages',
            name='name',
        ),
        migrations.AddField(
            model_name='occurrencenaturalarea',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occurrencetaxon',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slimemolddetails',
            name='lifestages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.SlimeMoldLifestages'),
        ),
        migrations.AddField(
            model_name='slimemoldlifestages',
            name='sclerotium_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slimemoldlifestages',
            name='sclerotium_size',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='slimemoldlifestages',
            name='sporangia_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slimemoldlifestages',
            name='sporangia_size',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='slimemoldlifestages',
            name='streaming_body_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slimemoldlifestages',
            name='streaming_body_size',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='adult',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='adult_pregnant_or_young',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='early_instar_larva',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='early_instar_nymph',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='early_pupa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='egg',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='egg_mass',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='immature',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='juvenile',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='larva',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='late_instar_larva',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='late_instar_nymph',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='late_pupa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='na',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='nest',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='nymph',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='pupa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='senescent',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='subadult',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='animallifestages',
            name='unknown',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='pondlakeanimaldetails',
            name='lentic_size_acres_aprox',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pondlakeanimaldetails',
            name='lentic_size_acres_exact',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pondlakeanimaldetails',
            name='lentic_size_squaremeters_aprox',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pondlakeanimaldetails',
            name='lentic_size_squaremeters_exact',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='pondlakeanimaldetails',
            name='microhabitat_comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='pondlakeanimaldetails',
            name='pond_lake_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamanimaldetails',
            name='stream_name_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamanimaldetails',
            name='substrate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.StreamSubstrate'),
        ),
        migrations.AlterField(
            model_name='wetlandanimaldetails',
            name='lentic_size_acres_aprox',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wetlandanimaldetails',
            name='lentic_size_acres_exact',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='wetlandanimaldetails',
            name='lentic_size_squaremeters_aprox',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wetlandanimaldetails',
            name='lentic_size_squaremeters_exact',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='wetlandanimaldetails',
            name='wetland_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wetlandvetegationstructure',
            name='buttonbush',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='wetlandvetegationstructure',
            name='cattail',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='wetlandvetegationstructure',
            name='ferns',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='wetlandvetegationstructure',
            name='forbs',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='wetlandvetegationstructure',
            name='phragmites',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='wetlandvetegationstructure',
            name='sedges',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.DeleteModel(
            name='PlantDetails',
        ),
        migrations.DeleteModel(
            name='StreamSubstracte',
        ),
        migrations.AddField(
            model_name='mossdetails',
            name='lifestages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.MossLifestages'),
        ),
        migrations.AddField(
            model_name='mossdetails',
            name='moisture_regime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.MoistureRegime'),
        ),
        migrations.AddField(
            model_name='mossdetails',
            name='plant_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.PlantCount'),
        ),
        migrations.AddField(
            model_name='mossdetails',
            name='slope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Slope'),
        ),
        migrations.AddField(
            model_name='mossdetails',
            name='tree_canopy_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.CanopyCover'),
        ),
        migrations.AddField(
            model_name='floweringplantdetails',
            name='general_habitat_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.GeneralHabitatCategory'),
        ),
        migrations.AddField(
            model_name='floweringplantdetails',
            name='ground_surface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.GroundSurface'),
        ),
        migrations.AddField(
            model_name='floweringplantdetails',
            name='landscape_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.LandscapePosition'),
        ),
        migrations.AddField(
            model_name='floweringplantdetails',
            name='lifestages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.FloweringPlantLifestages'),
        ),
        migrations.AddField(
            model_name='floweringplantdetails',
            name='moisture_regime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.MoistureRegime'),
        ),
        migrations.AddField(
            model_name='floweringplantdetails',
            name='plant_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.PlantCount'),
        ),
        migrations.AddField(
            model_name='floweringplantdetails',
            name='slope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Slope'),
        ),
        migrations.AddField(
            model_name='floweringplantdetails',
            name='tree_canopy_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.CanopyCover'),
        ),
        migrations.AddField(
            model_name='ferndetails',
            name='general_habitat_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.GeneralHabitatCategory'),
        ),
        migrations.AddField(
            model_name='ferndetails',
            name='ground_surface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.GroundSurface'),
        ),
        migrations.AddField(
            model_name='ferndetails',
            name='landscape_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.LandscapePosition'),
        ),
        migrations.AddField(
            model_name='ferndetails',
            name='lifestages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.FernLifestages'),
        ),
        migrations.AddField(
            model_name='ferndetails',
            name='moisture_regime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.MoistureRegime'),
        ),
        migrations.AddField(
            model_name='ferndetails',
            name='plant_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.PlantCount'),
        ),
        migrations.AddField(
            model_name='ferndetails',
            name='slope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Slope'),
        ),
        migrations.AddField(
            model_name='ferndetails',
            name='tree_canopy_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.CanopyCover'),
        ),
        migrations.AddField(
            model_name='coniferdetails',
            name='disturbance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.DisturbanceType'),
        ),
        migrations.AddField(
            model_name='coniferdetails',
            name='earthworm_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.EarthwormEvidence'),
        ),
        migrations.AddField(
            model_name='coniferdetails',
            name='general_habitat_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.GeneralHabitatCategory'),
        ),
        migrations.AddField(
            model_name='coniferdetails',
            name='ground_surface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.GroundSurface'),
        ),
        migrations.AddField(
            model_name='coniferdetails',
            name='landscape_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.LandscapePosition'),
        ),
        migrations.AddField(
            model_name='coniferdetails',
            name='lifestages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.ConiferLifestages'),
        ),
        migrations.AddField(
            model_name='coniferdetails',
            name='moisture_regime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.MoistureRegime'),
        ),
        migrations.AddField(
            model_name='coniferdetails',
            name='plant_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.PlantCount'),
        ),
        migrations.AddField(
            model_name='coniferdetails',
            name='slope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Slope'),
        ),
        migrations.AddField(
            model_name='coniferdetails',
            name='tree_canopy_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.CanopyCover'),
        ),
    ]
