# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0006_auto_20170929_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedrockAndOutcrops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CMSensitivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlacialDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlacialDepositPleistoceneAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeapLandCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NaturalAreaCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NaturalAreaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegionalFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='occurrencenaturalarea',
            name='natural_area_element',
        ),
        migrations.AddField(
            model_name='elementnaturalareas',
            name='aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Aspect'),
        ),
        migrations.AddField(
            model_name='elementnaturalareas',
            name='disturbance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.DisturbanceType'),
        ),
        migrations.AddField(
            model_name='elementnaturalareas',
            name='earthworm_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.EarthwormEvidence'),
        ),
        migrations.AddField(
            model_name='elementnaturalareas',
            name='notable_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elementnaturalareas',
            name='slope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Slope'),
        ),
        migrations.AddField(
            model_name='occurrencenaturalarea',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.ElementNaturalAreas'),
        ),
        migrations.AlterField(
            model_name='coniferdetails',
            name='disturbance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.DisturbanceType'),
        ),
        migrations.AlterField(
            model_name='coniferdetails',
            name='earthworm_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.EarthwormEvidence'),
        ),
        migrations.AlterField(
            model_name='elementnaturalareas',
            name='landscape_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.LandscapePosition'),
        ),
        migrations.AlterField(
            model_name='ferndetails',
            name='disturbance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.DisturbanceType'),
        ),
        migrations.AlterField(
            model_name='ferndetails',
            name='earthworm_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.EarthwormEvidence'),
        ),
        migrations.AlterField(
            model_name='floweringplantdetails',
            name='disturbance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.DisturbanceType'),
        ),
        migrations.AlterField(
            model_name='floweringplantdetails',
            name='earthworm_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.EarthwormEvidence'),
        ),
        migrations.AlterField(
            model_name='mossdetails',
            name='disturbance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.DisturbanceType'),
        ),
        migrations.AlterField(
            model_name='mossdetails',
            name='earthworm_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfdcore.EarthwormEvidence'),
        ),
        migrations.AddField(
            model_name='elementnaturalareas',
            name='bedrock_and_outcrops',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.BedrockAndOutcrops'),
        ),
        migrations.AddField(
            model_name='elementnaturalareas',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.NaturalAreaCondition'),
        ),
        migrations.AddField(
            model_name='elementnaturalareas',
            name='glaciar_diposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.GlacialDeposit'),
        ),
        migrations.AddField(
            model_name='elementnaturalareas',
            name='leap_land_cover_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.LeapLandCover'),
        ),
        migrations.AddField(
            model_name='elementnaturalareas',
            name='pleistocene_glaciar_diposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.GlacialDepositPleistoceneAge'),
        ),
        migrations.AddField(
            model_name='elementnaturalareas',
            name='regional_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.RegionalFrequency'),
        ),
        migrations.AddField(
            model_name='elementnaturalareas',
            name='sensitivity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.CMSensitivity'),
        ),
        migrations.AddField(
            model_name='elementnaturalareas',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.NaturalAreaType'),
        ),
    ]
