# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0007_auto_20171009_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrencenaturalarea',
            old_name='details',
            new_name='element',
        ),
    ]
