# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0008_auto_20171009_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementnaturalareas',
            name='general_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='elementnaturalareas',
            name='natural_area_code_nac',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
