# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0010_auto_20171016_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitingbodiesage',
            name='aged_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fruitingbodiesage',
            name='buttons_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fruitingbodiesage',
            name='decomposing_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fruitingbodiesage',
            name='emergents_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fruitingbodiesage',
            name='mature_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fruitingbodiesage',
            name='young_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
