# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0011_auto_20171016_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observedassociations',
            old_name='ants_association_details',
            new_name='ants_association',
        ),
        migrations.RenameField(
            model_name='observedassociations',
            old_name='badger_association_details',
            new_name='badger_association',
        ),
        migrations.RenameField(
            model_name='observedassociations',
            old_name='beetles_association_details',
            new_name='beetles_association',
        ),
        migrations.RenameField(
            model_name='observedassociations',
            old_name='chipmunk_association_details',
            new_name='chipmunk_association',
        ),
        migrations.RenameField(
            model_name='observedassociations',
            old_name='deer_association_details',
            new_name='deer_association',
        ),
        migrations.RenameField(
            model_name='observedassociations',
            old_name='easter_gray_squirrel_association_details',
            new_name='easter_gray_squirrel_association',
        ),
        migrations.RenameField(
            model_name='observedassociations',
            old_name='gnat_association_details',
            new_name='gnat_association',
        ),
        migrations.RenameField(
            model_name='observedassociations',
            old_name='other_small_rodent_association_details',
            new_name='other_small_rodent_association',
        ),
        migrations.RenameField(
            model_name='observedassociations',
            old_name='skunk_association_details',
            new_name='skunk_association',
        ),
        migrations.RenameField(
            model_name='observedassociations',
            old_name='slug_association_details',
            new_name='slug_association',
        ),
        migrations.RenameField(
            model_name='observedassociations',
            old_name='snail_association_details',
            new_name='snail_association',
        ),
        migrations.RenameField(
            model_name='observedassociations',
            old_name='snow_flea_association_details',
            new_name='snow_flea_association',
        ),
        migrations.RenameField(
            model_name='observedassociations',
            old_name='termite_association_details',
            new_name='termite_association',
        ),
        migrations.RenameField(
            model_name='observedassociations',
            old_name='turtle_association_details',
            new_name='turtle_association',
        ),
    ]
