# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0012_auto_20171016_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='occurrence_fk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
