# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0014_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.TextField(blank=True, help_text='Note to show together with the UI page'),
        ),
        migrations.AlterField(
            model_name='note',
            name='ui_tab',
            field=models.CharField(help_text='Identifier of the UI page where this note should be shown', max_length=50),
        ),
    ]
