# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0015_auto_20180207_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landanimaldetails',
            name='diseases_and_abnormalities',
        ),
        migrations.RemoveField(
            model_name='pondlakeanimaldetails',
            name='diseases_and_abnormalities',
        ),
        migrations.RemoveField(
            model_name='streamanimaldetails',
            name='diseases_and_abnormalities',
        ),
        migrations.RemoveField(
            model_name='wetlandanimaldetails',
            name='diseases_and_abnormalities',
        ),
    ]
