# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 15:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0016_auto_20180212_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='landanimaldetails',
            name='diseases_and_abnormalities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pondlakeanimaldetails',
            name='diseases_and_abnormalities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streamanimaldetails',
            name='diseases_and_abnormalities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wetlandanimaldetails',
            name='diseases_and_abnormalities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
