# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0017_auto_20180212_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landanimaldetails',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='landanimaldetails',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='pondlakeanimaldetails',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='pondlakeanimaldetails',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='streamanimaldetails',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='streamanimaldetails',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='wetlandanimaldetails',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='wetlandanimaldetails',
            name='marks',
        ),
    ]
