# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 12:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0022_auto_20180220_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsn', models.PositiveIntegerField()),
                ('name', models.CharField(help_text='Scientific name for the taxon, according to ITIS database', max_length=255)),
                ('common_names', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('rank', models.CharField(max_length=15)),
                ('upper_ranks', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('native', models.NullBooleanField(default=False)),
                ('other_code', models.TextField(blank=True)),
                ('ibp_english', models.CharField(blank=True, max_length=4)),
                ('ibp_scientific', models.CharField(blank=True, max_length=6)),
                ('bblab_number', models.CharField(blank=True, max_length=6)),
                ('nrcs_usda_symbol', models.TextField(blank=True)),
                ('synonym_nrcs_usda_symbol', models.TextField(blank=True)),
                ('epa_numeric_code', models.CharField(blank=True, max_length=255)),
                ('cm_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.CmStatus')),
                ('g_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.GRank')),
                ('iucn_red_list_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.IucnRedListCategory')),
                ('n_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.NRank')),
                ('oh_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.RegionalStatus')),
                ('s_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.SRank')),
                ('usfws_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.UsfwsStatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
