# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 15:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0023_taxon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxon',
            options={'verbose_name_plural': 'taxa'},
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='id',
        ),
        migrations.AlterField(
            model_name='taxon',
            name='common_names',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='name',
            field=models.CharField(editable=False, help_text='Scientific name for the taxon, according to ITIS database', max_length=255),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='rank',
            field=models.CharField(editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='tsn',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='upper_ranks',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True),
        ),
    ]
