# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0024_auto_20180222_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='kingdom',
            field=models.CharField(default='dummy', editable=False, max_length=15),
            preserve_default=False,
        ),
    ]
