# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0025_taxon_kingdom'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencetaxon',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfdcore.Taxon'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='name',
            field=models.CharField(editable=False, help_text='Scientific name for the taxon', max_length=255),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='tsn',
            field=models.PositiveIntegerField(help_text='Taxonomic Serial Number, as found on the Integrated Taxonomic Information System (ITIS)', primary_key=True, serialize=False),
        ),
    ]
