# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0026_auto_20180222_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementspecies',
            name='cm_status',
        ),
        migrations.RemoveField(
            model_name='elementspecies',
            name='g_rank',
        ),
        migrations.RemoveField(
            model_name='elementspecies',
            name='iucn_red_list_category',
        ),
        migrations.RemoveField(
            model_name='elementspecies',
            name='n_rank',
        ),
        migrations.RemoveField(
            model_name='elementspecies',
            name='oh_status',
        ),
        migrations.RemoveField(
            model_name='elementspecies',
            name='s_rank',
        ),
        migrations.RemoveField(
            model_name='elementspecies',
            name='usfws_status',
        ),
        migrations.RemoveField(
            model_name='species',
            name='element_species',
        ),
        migrations.RemoveField(
            model_name='occurrencetaxon',
            name='species',
        ),
        migrations.DeleteModel(
            name='ElementSpecies',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
