# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 13:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0027_auto_20180223_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coniferlifestages',
            name='immature_ovulate_cones',
        ),
        migrations.RemoveField(
            model_name='coniferlifestages',
            name='immature_pollen_cones',
        ),
        migrations.RemoveField(
            model_name='coniferlifestages',
            name='mature_ovulate_cones',
        ),
        migrations.RemoveField(
            model_name='coniferlifestages',
            name='mature_pollen_cones',
        ),
        migrations.RemoveField(
            model_name='coniferlifestages',
            name='spent_ovulate_cones',
        ),
        migrations.RemoveField(
            model_name='coniferlifestages',
            name='spent_pollen_cones',
        ),
        migrations.RemoveField(
            model_name='coniferlifestages',
            name='vegetative',
        ),
        migrations.AddField(
            model_name='coniferlifestages',
            name='code',
            field=models.TextField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coniferlifestages',
            name='name',
            field=models.TextField(default='dummy'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='coniferdetails',
            name='lifestages',
        ),
        migrations.AddField(
            model_name='coniferdetails',
            name='lifestages',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
