# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0029_auto_20180226_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalLifestages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
