# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0030_animallifestages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slimemolddetails',
            name='lifestages',
        ),
        migrations.DeleteModel(
            name='SlimeMoldLifestages',
        ),
    ]
