# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfdcore', '0035_auto_20180228_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlimeMoldLifestages',
        ),
        migrations.RemoveField(
            model_name='slimemolddetails',
            name='lifestages',
        ),
        migrations.AddField(
            model_name='slimemolddetails',
            name='sclerotium_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slimemolddetails',
            name='sclerotium_size',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='slimemolddetails',
            name='sporangia_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slimemolddetails',
            name='sporangia_size',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='slimemolddetails',
            name='streaming_body_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slimemolddetails',
            name='streaming_body_size',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
